### PR TITLE
automatic crawler update (10/21/2019)

### PR DESCRIPTION
**Pull request by ryancdickson**
@lachellel 

Please find the weekly Federal PKI Crawler/Graph update (October 21, 2019 execution).
<br> 

**Live Preview**: https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/fpki-guides/20191021-auto-fpki-graph-update/tools/fpkigraph/

<br>

**Nodes Added or Removed (compared to 10/14/2019 execution):**
- N1 (REMOVED): CN=DOD EMAIL CA-33,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N2 (REMOVED): CN=DOD EMAIL CA-34,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N3 (REMOVED): CN=DOD EMAIL CA-39,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N4 (REMOVED): CN=DOD EMAIL CA-40,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N5 (REMOVED): CN=DOD EMAIL CA-41,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N6 (REMOVED): CN=DOD EMAIL CA-42,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N7 (REMOVED): CN=DOD EMAIL CA-43,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N8 (REMOVED): CN=DOD EMAIL CA-44,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N9 (REMOVED): CN=DOD EMAIL CA-49,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N10 (REMOVED): CN=DOD EMAIL CA-50,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N11 (REMOVED): CN=DOD EMAIL CA-51,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N12 (REMOVED): CN=DOD EMAIL CA-52,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N13 (REMOVED): CN=DOD EMAIL CA-59,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N14 (REMOVED): CN=DOD ID CA-33,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N15 (REMOVED): CN=DOD ID CA-34,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N16 (REMOVED): CN=DOD ID CA-39,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N17 (REMOVED): CN=DOD ID CA-40,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N18 (REMOVED): CN=DOD ID CA-41,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N19 (REMOVED): CN=DOD ID CA-42,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N20 (REMOVED): CN=DOD ID CA-43,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N21 (REMOVED): CN=DOD ID CA-44,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N22 (REMOVED): CN=DOD ID CA-49,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N23 (REMOVED): CN=DOD ID CA-50,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N24 (REMOVED): CN=DOD ID CA-51,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N25 (REMOVED): CN=DOD ID CA-52,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N26 (REMOVED): CN=DOD ID CA-59,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N27 (REMOVED): CN=DOD ID SW CA-35,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N28 (REMOVED): CN=DOD ID SW CA-36,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N29 (REMOVED): CN=DOD ID SW CA-37,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N30 (REMOVED): CN=DOD ID SW CA-38,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N31 (REMOVED): CN=DOD ID SW CA-45,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N32 (REMOVED): CN=DOD ID SW CA-46,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N33 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N34 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N35 (REMOVED): CN=DOD SW CA-53,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N36 (REMOVED): CN=DOD SW CA-54,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N37 (REMOVED): CN=DOD SW CA-60,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N38 (REMOVED): CN=ECA Root CA 2,OU=ECA,O=U.S. Government,C=US
- N39 (REMOVED): CN=ECA Root CA 4,OU=ECA,O=U.S. Government,C=US
- N40 (REMOVED): CN=IdenTrust ECA 4,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- N41 (REMOVED): CN=IdenTrust ECA 5,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- N42 (REMOVED): CN=IdenTrust ECA Component S21,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- N43 (REMOVED): CN=IdenTrust ECA S21,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- N44 (REMOVED): CN=IdenTrust ECA S22,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- N45 (REMOVED): CN=IdenTrust ECA S22C,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- N46 (REMOVED): CN=ORC ECA 6,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- N47 (REMOVED): CN=ORC ECA HW 5,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- N48 (REMOVED): CN=ORC ECA SW 5,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- N49 (REMOVED): CN=US DoD CCEB Interoperability Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US
- N50 (REMOVED): CN=WidePoint ORC ECA 7,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
<br>

**Edges Added or Removed (compared to 10/14/2019 execution):**
- E1 (REMOVED): CN=Australian Defence Interoperability CA,OU=CAs,OU=PKI,OU=DoD,O=GOV,C=AU -> CN=US DoD CCEB Interoperability Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E2 (REMOVED): CN=DoD Interoperability Root CA 1,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E3 (REMOVED): CN=DoD Interoperability Root CA 1,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=ECA Root CA 2,OU=ECA,O=U.S. Government,C=US
- E4 (REMOVED): CN=DoD Interoperability Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E5 (REMOVED): CN=DoD Interoperability Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=ECA Root CA 4,OU=ECA,O=U.S. Government,C=US
- E6 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-33,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E7 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-34,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E8 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-39,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E9 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-40,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E10 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-33,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E11 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-34,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E12 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-39,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E13 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-40,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E14 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID SW CA-35,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E15 (REMOVED): CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID SW CA-36,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E16 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-41,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E17 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-42,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E18 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-43,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E19 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-44,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E20 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-49,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E21 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-50,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E22 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-51,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E23 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-52,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E24 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-59,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E25 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-41,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E26 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-42,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E27 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-43,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E28 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-44,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E29 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-49,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E30 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-50,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E31 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-51,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E32 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-52,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E33 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID CA-59,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E34 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID SW CA-37,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E35 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID SW CA-38,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E36 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID SW CA-45,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E37 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD ID SW CA-46,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E38 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD SW CA-53,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E39 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD SW CA-54,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E40 (REMOVED): CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD SW CA-60,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E41 (REMOVED): CN=ECA Root CA 2,OU=ECA,O=U.S. Government,C=US -> CN=IdenTrust ECA 4,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E42 (REMOVED): CN=ECA Root CA 2,OU=ECA,O=U.S. Government,C=US -> CN=IdenTrust ECA 5,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E43 (REMOVED): CN=ECA Root CA 2,OU=ECA,O=U.S. Government,C=US -> CN=ORC ECA HW 5,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E44 (REMOVED): CN=ECA Root CA 2,OU=ECA,O=U.S. Government,C=US -> CN=ORC ECA SW 5,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E45 (REMOVED): CN=ECA Root CA 4,OU=ECA,O=U.S. Government,C=US -> CN=IdenTrust ECA Component S21,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E46 (REMOVED): CN=ECA Root CA 4,OU=ECA,O=U.S. Government,C=US -> CN=IdenTrust ECA S21,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E47 (REMOVED): CN=ECA Root CA 4,OU=ECA,O=U.S. Government,C=US -> CN=IdenTrust ECA S22,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E48 (REMOVED): CN=ECA Root CA 4,OU=ECA,O=U.S. Government,C=US -> CN=IdenTrust ECA S22C,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E49 (REMOVED): CN=ECA Root CA 4,OU=ECA,O=U.S. Government,C=US -> CN=ORC ECA 6,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E50 (REMOVED): CN=ECA Root CA 4,OU=ECA,O=U.S. Government,C=US -> CN=WidePoint ORC ECA 7,OU=Certification Authorities,OU=ECA,O=U.S. Government,C=US
- E51 (REMOVED): CN=US DoD CCEB Interoperability Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DoD Root CA 3,OU=PKI,OU=DoD,O=U.S. Government,C=US
- E52 (REMOVED): OU=Entrust Managed Services Root CA,OU=Certification Authorities,O=Entrust,C=US -> OU=Entrust Managed Services Root CA,OU=Certification Authorities,O=Entrust,C=US
- E53 (REMOVED): OU=Entrust Managed Services Root CA,OU=Certification Authorities,O=Entrust,C=US -> OU=Entrust Managed Services Root CA,OU=Certification Authorities,O=Entrust,C=US
- E54 (REMOVED): OU=Entrust Managed Services Root CA,OU=Certification Authorities,O=Entrust,C=US -> OU=Entrust Managed Services SSP CA,OU=Certification Authorities,O=Entrust,C=US

<br>

**Root Cause Analysis:** 
- E52/E53/E54: Entrust cleaned up http://rootweb.managed.entrust.com/AIA/CertsIssuedToEMSRootCA.p7c to remove self-signed (link) certificates noted in #566. Edge E54 (see above) was also removed in the clean-up effort as there are no valid end-entity certificates signed by its private key.  The bundle now only includes certificates issued to the Entrust Managed Services Root CA from the Federal Common Policy CA. 
- Everything else: DoD appears to be having issues with their Global Directory Service. All bundle URLs (for example,  http://crl.disa.mil/issuedto/DODINTEROPERABILITYROOTCA2_IT.p7c) 404'd. The issue appears to have started on Saturday. I'll make sure our colleagues are aware (though I'm sure they are!).
<br>

**Other Updates:**
- N/A

<br>	
Please let me know if there are any questions.

### CODE REVIEW

**Comment by lachellel** [comment]
@ryancdickson 

I'd like to see the sunset or "to be sunset soon" CAs operated by DoD removed from the graph and the bundles.  That's a wish for simple 'cleanliness', performance, and reducing confusion for other agencies.   However, I can't in good faith publish the graph with 51+ data points removed! 

Recommend:  Close and reprocess the scripts.  I was able to fetch at least one bundle 45 seconds ago.

**Comment by ryancdickson** [comment]
Will do.

I'm still 404'ing on a few URLs, but I'll periodically check until we're back up.

Attempted URLs:
- http://crl.disa.mil/issuedto/DODINTEROPERABILITYROOTCA1_IT.p7c (works)
- http://crl.disa.mil/issuedto/DODINTEROPERABILITYROOTCA2_IT.p7c (fails)
- http://crl.disa.mil/issuedto/DODROOTCA2_IT.p7c (works)
- http://crl.disa.mil/issuedto/DODROOTCA3_IT.p7c (fails)
- http://crl.disa.mil/issuedto/ECAROOTCA2_IT.p7c (works)
- http://crl.disa.mil/issuedto/ECAROOTCA4_IT.p7c (works)

**Comment by jsalga01** [comment]
Ryan,

All URLs are working. Let me know if you are seeing the same. Thanks.

**Comment by ryancdickson** [comment]
@jsalga01 - Yep! I'll be running the Crawler/Graph update again today. Thanks for helping to nudge this along =)

**Pull request closed without merging**
