### PR TITLE
Create new page for FPKI OCSP, AIA, CDP, and DN

### LINKED ISSUE #68: Pairing of certificates with the URIs for OCSP,CDP, and AIA

### LINKED ISSUE #69: List of Federal PKI issuer base DNs for certificate mapping expressions

### PR DESCRIPTION
**Pull request by weirdscience**
First start at a single location for all CDP, AIA, OCSP, and DN. I think a machine readable format would be better or maybe both. If this format works, I will collect and convert for the other FPKI CAs. This should resolve #69 and resolve #68.

### CODE REVIEW

**Comment by lachellel** [comment]
do you want to push to this branch (drafts-fpkima) or the staging?

1. What do you want the page title and label to be?  (we need to add the front matter)
2.  Machine readable format - what about a json file and we can see if it can be generated / stored in _data, then **displayed** in a page (for user readable); all from the same file? 

Thoughts on 2 above?

**Comment by grandamp** [comment]
+1 for json

I would be happy to contribute data...

Are these the values included within each of the cross certificates, or are
the URLs for products signed by the cross certificates?

I.e., crls and ocsp URLs to validate certificates signed by each CA key, or
to validate the cross certificate that is identified?

**Comment by weirdscience** [comment]
I'm for JSON, XML, CSV, or whatever is easier for engineers or admins. Push to the staging branch if that works. I'll try to work from the MA drafts branch but it doesn't have the latest entries.

I think this should be its own page under maybe the tools directory. I have some crawler and graph faq guides I was going to convert.

Entries gathered from end entity or CA certs. 100% sure on the HTTP CRL, but not sure of OCSP and AIA. Feel free to check if they are accurate.

**Comment by weirdscience** [comment]
Is this good to merge?

**Comment by lachellel** [comment]
i'll merge for initial so we can iterate together
This doesn't include all end entity certificates and URIs - which are the largest pieces
I do think we should use _data and make this a json file type so it can be parsed (**and** also updated via scripts from the aia crawler and other SIA/AIA chases)

**Comment by weirdscience** [comment]
This table came up at the TWG last week. Any way we can get some feedback and publish it with updated data?

It's also missing SIA values.

**Pull request merged**
