### PR TITLE
automatic crawler update

### PR DESCRIPTION
**Pull request by maxwellfunk**
Automatic crawler update for 12/23/2019.

### CODE REVIEW

**Comment by lachellel** [comment]
@maxwellfunk 

Can we rerun?  There are six (6) missing from the Federal Bridge CA G4 "issued by/ issued to":

image

**Comment by maxwellfunk** [comment]
@lachellel this was automatically run on Ryan's machine.  Would need to install java files locally to regenerate and submit manual changes.  I am not very familiar with the tools so risk of errors would be high.  It should rerun on 12/30 as well.

**Comment by grandamp** [comment]
Afternoon!  If the crawler code were open source, I would be happy to search and contribute.

As an alternative, I performed a crawl of all SIA HTTP artifacts using this implementation:

- https://github.com/grandamp/KSValidationService

[Attached is the output in a .zip file](https://github.com/GSA/fpki-guides/files/3995832/discovery.zip), that contains:

- output.html (provides info on what was discovered and URL info)
- service.log (provides detail on any errors that occurred)
- discovered.pem (all the discovered certs in PEM form)
- discovered.p7b (`openssl crl2pkcs7 -outform DER -out discovered.p7b -nocrl -certfile discovered.pem`)

**Comment by lachellel** [comment]
@maxwellfunk 
okay!

I reran it and only updated the actual graphfile  (gexf).  A local build of the site was successful.  Added commit to the graph update branch to kick off a new preview.

**Comment by lachellel** [comment]
@maxwellfunk yes - looks like it's building too.  I did a shortcut in one of the commits, and accidentally introduced line ending errors. :-1: 

Will merge and push.

**Pull request merged**
