### PR TITLE
automatic crawler update (cumulative)

### PR DESCRIPTION
**Pull request by ryancdickson**
@lachellel @djpackham

Please find the weekly FPKI Crawler/Graph update, enclosed.

Live Preview: https://federalist-proxy.app.cloud.gov/preview/gsa/fpki-guides/20190128-auto-fpki-graph-update/tools/fpkigraph/

### **1/28/19 Execution:**
_Nodes Added or Removed (compared to 1/21/2019 execution):_
- N/A - no changes from 1/21/19 execution.
	
_Edges Added or Removed (compared to 1/21/2019 execution):_
- N/A - no changes from 1/21/19 execution.

_Root Cause Analysis:_
- N/A - no changes from 1/21/19 execution.

<br>

### **1/21/19 Execution:**
_Nodes Added or Removed (compared to 1/14/2019 execution):_
-  REMOVED: CN=DOD CA-31,OU=PKI,OU=DoD,O=U.S. Government,C=US
-  REMOVED: CN=DOD EMAIL CA-31,OU=PKI,OU=DoD,O=U.S. Government,C=US
-  REMOVED: OU=Fiscal Service,OU=Department of the Treasury,O=U.S. Government,C=US (SHA1, Serial: 46eacea1)
	
_Edges Added or Removed (compared to 1/14/2019 execution):_
-  REMOVED: CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD CA-31,OU=PKI,OU=DoD,O=U.S. Government,C=US
-  REMOVED: CN=DoD Root CA 2,OU=PKI,OU=DoD,O=U.S. Government,C=US -> CN=DOD EMAIL CA-31,OU=PKI,OU=DoD,O=U.S. Government,C=US
-  REMOVED: OU=US Treasury Root CA,OU=Certification Authorities,OU=Department of the Treasury,O=U.S. Government,C=US -> OU=Fiscal Service,OU=Department of the Treasury,O=U.S. Government,C=US (SHA1, Serial: 46eacea1)

_Root Cause Analysis:_
- CN=DOD CA-31,OU=PKI,OU=DoD,O=U.S. Government,C=US expired at 2019-01-16 14:49:30 GMT
- CN=DOD EMAIL CA-31,OU=PKI,OU=DoD,O=U.S. Government,C=US expired at 2019-01-16 14:52:43 GMT
- OU=Fiscal Service,OU=Department of the Treasury,O=U.S. Government,C=US (SHA1, Serial: 46eacea1) expired at ‎Friday, ‎January ‎18, ‎2019 9:48:31 AM

<br>

### **1/14/19 Execution:**
_Nodes Added or Removed (compared to 1/7/2019 execution):_
- ADDED: CN=Alexion Pharmaceuticals Root CA,OU=CAs,O=Alexion Pharmaceuticals,C=US
	
_Edges Added or Removed (compared to 1/7/2019 execution):_
- ADDED: CN=Alexion Pharmaceuticals Root CA,OU=CAs,O=Alexion Pharmaceuticals,C=US -> CN=Alexion Pharmaceuticals Root CA,OU=CAs,O=Alexion Pharmaceuticals,C=US
	
_Root Cause Analysis:_
- Previous executions of Crawler returned no data at http://cacer.symauth.com/mpki/issuedto_AlexionRootCA.p7c. 
	```ERROR: did retrieve any bytes at uri http://cacer.symauth.com/mpki/issuedto_AlexionRootCA.p7c```
- The URI now appears accessible/corrected.

<br>

### **1/7/19 Execution:**
_Nodes Added or Removed (compared to 12/31/2018 execution):_
- N/A - no changes from 12/31/18 execution.
	
_Edges Added or Removed (compared to 12/31/2018 execution):_
- N/A - no changes from 12/31/18 execution.
	
_Root Cause Analysis:_
- N/A - no changes from 12/31/18 execution.

<br>

### **12/31/18 Execution:**
_Nodes Added or Removed (compared to 12/24/2018 execution):_
- N/A - no changes from 12/24/18 execution.
	
_Edges Added or Removed (compared to 12/24/2018 execution):_
- N/A - no changes from 12/24/18 execution.
	
_Root Cause Analysis:_
- N/A - no changes from 12/24/18 execution.

<br>

### **12/24/18 Execution:**
_Nodes Added or Removed (compared to 12/17/2018 execution):_
- ADDED: CN=DigiCert Federal SSP Intermediate CA - G5,O=DigiCert,Inc.,C=US
- ADDED: CN=IdenTrust SAFE-BioPharma CA 1,OU=IdenTrust Global Common,O=IdenTrust,C=US

_Edges Added or Removed (compared to 12/17/2018 execution):_
- ADDED: CN=Federal Common Policy CA,OU=FPKI,O=U.S. Government,C=US -> CN=DigiCert Federal SSP Intermediate CA - G5,O=DigiCert,Inc.,C=US
- ADDED: CN=SAFE Bridge CA 02,OU=Certification Authorities,O=SAFE-Biopharma,C=US -> CN=IdenTrust SAFE-BioPharma CA 1,OU=IdenTrust Global Common,O=IdenTrust,C=US
	
_Root Cause Analysis:_
- Both new CA certificates were not publicly available at the time of the 12/17/2018 execution (at 9am).
	- CN=DigiCert Federal SSP Intermediate CA - G5,O=DigiCert,Inc.,C=US (issued 12/13/2018, first seen Dec. 17, 2018, 1:53 p.m.)
	- CN=IdenTrust SAFE-BioPharma CA 1,OU=IdenTrust Global Common,O=IdenTrust,C=US (issued 12/11/2018, first seen Dec. 19, 2018, 9:30 a.m.)

<br>
	
Please let me know if there are any questions.

Thanks,
Ryan

### CODE REVIEW

**Comment by lachellel** [comment]
@ryancdickson 

For clarity - for the CAs that were removed (i.e. DOD CA-31):

- Was the CA removed due to the CA cert artifact **no longer being published** (the CA was properly shut down)? 
- OR, was the CA removed due to the code encountering an expiration date for the CA cert in the SIA/AIA?

**Comment by ryancdickson** [comment]
Nice to have you back =)

- DOD CA-31 and DOD EMAIL CA-31 are still being published at http://crl.disa.mil/issuedby/DODROOTCA2_IB.p7c (DoD Root CA 2's SIA (issued by DoD Interop. Root CA 1)). 
- OU=Fiscal Service,OU=Department of the Treasury,O=U.S. Government,C=US (SHA1, Serial: 46eacea1) is still being published at http://pki.treasury.gov/root_sia.p7c  (US Treasury Root CA's SIA (issued by COMMON).

That said, the pruning appears to be at the hands of Crawler logic.

**Comment by lachellel** [comment]
@grandamp 

- For the Fiscal Service CA (OU=Fiscal Service,OU=Department of the Treasury,O=U.S. Government,C=US) - was this CA terminated or rekeyed?  If rekeyed, was a new CA cert published to the SIA?

[Inquiring minds]

**Comment by jsalga01** [comment]
> Nice to have you back =)
> 
> DOD CA-31 and DOD EMAIL CA-31 are still being published at http://crl.disa.mil/issuedby/DODROOTCA2_IB.p7c (DoD Root CA 2's SIA (issued by DoD Interop. Root CA 1)).
> OU=Fiscal Service,OU=Department of the Treasury,O=U.S. Government,C=US (SHA1, Serial: 46eacea1) is still being published at http://pki.treasury.gov/root_sia.p7c  (US Treasury Root CA's SIA (issued by COMMON).
> 
> That said, the pruning appears to be at the hands of Crawler logic.

Ryan, a request was submitted last week to the GDS team to remove DoD [EMAIL] CAs 31-32 from the SIA location. It could take up to 2 weeks for the certs to be removed.  John

**Pull request merged**
