### PR TITLE
Color-coded HTML tables for Affiliate Status

### LINKED ISSUE #330: Update Affiliate Table Format in FPKIAR
#### Description of Issue: ####
The community asked if the FPKI activity report affiliate status table could be updated to its original color coded format.

#### Details of Issue: ####
The monthly statistical report included a color coded legend which did not make it into the github page.

#### References (Docs, Links, Files): ####
Activity Report - https://fpki.idmanagement.gov/tools/fpkiactivityreport/

#### If a New Page or Content is Needed, Expected Outcomes: ####
The new affiliate status table will include a color coded legend.

### PR DESCRIPTION
**Pull request by weirdscience**
One of the feedback items on the activity report were color-coded tables to help quickly identify any affiliates with an issue. This fixes #330 . Thank you @ryancdickson for the help in identifying the bootstrap issue.

### CODE REVIEW

**Comment by weirdscience** [comment]
@lachellel I checked the build and new activity report page renders well.

**Comment by lachellel** [comment]
@weirdscience 
https://designsystem.digital.gov/components/colors/

I just want to run it by rachel / comms for a quick look at the colors?  We might need to change the color codes slightly to align with accessibility requirements!

**Comment by lachellel** [comment]
@RachelF

Here is the link - https://federalist-proxy.app.cloud.gov/preview/gsa/fpki-guides/fpkiar-html-tables/tools/fpkiactivityreport/

Will these colors work for accessibility? Or should we modify? 

If we need to modify, are the choices outlined [here](https://designsystem.digital.gov/components/colors/) still valid to choose from?

**Comment by weirdscience** [comment]
Great idea. I can also switch them to match the palette.

**Comment by RachelF** [comment]
I'd recommend switching to match the palette. The existing colors are
pretty harsh and look out of place with the other colors.


U.S. General Services Administration

Rachel Flagg

Digital Strategy & Content Management

Office of Government-wide Policy

**Comment by weirdscience** [comment]
Thank you, @RachelF ! @lachellel I've updated the palette. Checks valid.

Please review and approve.

**Pull request merged**
