### PR TITLE
automatic crawler update (10/14/2019)

### PR DESCRIPTION
**Pull request by ryancdickson**
@lachellel 

Please find the weekly Federal PKI Crawler/Graph update (October 14, 2019 execution).
<br> 

**Live Preview**: https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/gsa/fpki-guides/20191014-auto-fpki-graph-update/tools/fpkigraph/

<br>

**Nodes Added or Removed (compared to 10/07/2019 execution):**
- N/A. No change.

<br>

**Edges Added or Removed (compared to 10/07/2019 execution):**
- E1 (REMOVED): OU=Entrust Managed Services Root CA,OU=Certification Authorities,O=Entrust,C=US -> OU=Entrust Managed Services Root CA,OU=Certification Authorities,O=Entrust,C=US
- E2 (REMOVED): OU=Entrust Managed Services Root CA,OU=Certification Authorities,O=Entrust,C=US -> OU=Entrust Managed Services Root CA,OU=Certification Authorities,O=Entrust,C=US

<br>

**Root Cause Analysis:** 
- E1/E2: Entrust updated http://rootweb.managed.entrust.com/AIA/CertsIssuedToEMSRootCA.p7c to remove two of the self-signed entries for the Entrust Managed Services Root CA. The bundle now includes two self-signed entries and three entries issued to the Entrust Managed Services Root CA by the Federal Common Policy CA (5 certificates total). Previously, http://rootweb.managed.entrust.com/AIA/CertsIssuedToEMSRootCA.p7c was updated to only include the certificates issued to the Entrust Managed Services Root CA from the Federal Common Policy CA. I'll try to learn more about this change.  
	
<br>

**Other Updates:**
- N/A

<br>	
Please let me know if there are any questions.

### CODE REVIEW

**Comment by lachellel** [comment]
@ryancdickson 

Observation - these are link certs used primarily for rekeys in this particular "approach" (software / CAs):  

- Two different CA certs
- Different public keys
- Different Valid from dates / similar Valid To dates
- Different CDP values (one is EMSRootCA2.crl the other is EMSRootCA3.crl)
- one has AKI "A" and SKI "B" while the other has AKI "B" and SKI "A"
- One is asserting an unpublished EKU policy OID

**Comment by lachellel** [comment]
I'm going to merge for the graph update. 

Feel free to comment on the p7b and paths being built.

**Comment by ryancdickson** [comment]
I'll follow-up to a thread I have with Patrick and will report back. 

We had done some work to clean the bundle to only include the certs issued to the Entrust Managed Services Root from the Federal Common Policy CA. Immediately after the Entrust Managed Services Root re-key, the bundle hosted 3 certificates (all signed by the Federal Common Policy CA). The bundle later grew to 7 certs, and is now back down to 5. 

I thought in one of our past team discussions we determined link certs wouldn't be published - but perhaps that was an internal sync where we were iterating potential courses of action. 

More to come...

**Comment by ryancdickson** [comment]
**Following-up:** Entrust cleaned http://rootweb.managed.entrust.com/AIA/CertsIssuedToEMSRootCA.p7c to only include the certificates issued to the Entrust Managed Services Root CA from the Federal Common Policy CA. The bundle now only includes two certificates:

### Bundle Contents

Certificate 1:
- Subject: OU = Entrust Managed Services Root CA, OU = Certification Authorities, O = Entrust, C = US
- Issuer: CN = Federal Common Policy CA, OU = FPKI, O = U.S. Government, C = US
- Validity: 7/30/2015 to 7/30/2025
- Serial: 2e26
- SHA-1 Hash: 39c1d3b64e756a3267bfe5fecb103da892ca0611

<br>

Certificate 2:
- Subject: OU = Entrust Managed Services Root CA, OU = Certification Authorities, O = Entrust, C = US
- Issuer: CN = Federal Common Policy CA, OU = FPKI, O = U.S. Government, C = US
- Validity: 8/14/2019 to 8/14/2029
- Serial: 734a
- SHA-1 Hash: a09655170c87d0fbfe0328b99a7baf4a1cf0b5d9
<br>

### Certificates removed from bundle
Certificate 1 (Removed from Bundle):
- Subject: OU = Entrust Managed Services Root CA, OU = Certification Authorities, O = Entrust, C = US
- Issuer: CN = Federal Common Policy CA, OU = FPKI, O = U.S. Government, C = US
- Validity:  12/15/2010 to 12/15/2020
- Serial:  0202
- SHA-1 Hash:  50f68cb28f9a9b7fbb06ac452a827a31ca9bc55e
<br>

Certificate 2 (Removed from Bundle):
- Subject: OU = Entrust Managed Services Root CA, OU = Certification Authorities, O = Entrust, C = US
- Issuer: OU = Entrust Managed Services Root CA, OU = Certification Authorities, O = Entrust, C = US
- Validity:  8/13/2019 to 7/23/2025
- Serial: 4481077c
- SHA-1 Hash: eef2e3b80bb276f4231d0365f97890e0f70af8dd 
<br>

Certificate 3 (Removed from Bundle):
- Subject: OU = Entrust Managed Services Root CA, OU = Certification Authorities, O = Entrust, C = US
- Issuer: OU = Entrust Managed Services Root CA, OU = Certification Authorities, O = Entrust, C = US
- Validity: 7/23/2015 to 7/23/2025 
- Serial:  4481077b
- SHA-1 Hash:  855d98c924b3ee6216b1b8e25b4342f70565c394

**Pull request merged**
