### PR TITLE
CRLs and Certificates Playbook

### PR DESCRIPTION
**Pull request by dasgituser**
Shortened/streamlined.  Note:  could not get block indent to render correctly in https://dasgituser.github.io/fpki-guides/ -- though it renders correctly in my repository preview and I believe I have the markdown syntax correct.  Please let me know if block indent renders correctly when you render on GSA side.

### CODE REVIEW

**Comment by djpackham** [comment]
@dasgituser - Thanks. I have some feedback I am writing. Hope to get it over to you shortly before accepting this pull request.

**Comment by djpackham** [comment]
@dasgituser 

Awesome stuff!  I took your latest file and added some suggested updates to make the wording even simpler. Let me know what you think. I didn't get to the CRL section. Also, what do you think about turning the links at the bottom of the page for the CRLs and Certs into a table?

You can see my proposed updates here:
- GitHub Pages view - https://djpackham.github.io/fpki-guides/crls/
- Source Page - https://github.com/djpackham/fpki-guides/blob/gh-pages/pages/fpki_crls.md

**Comment by lachellel** [comment]
i like the wording and how it's playing out - very cool imo!

the "what is a certificate" and "what is a certificate policy" might be better in the overview and other page 
and then this page focuses on CRLs, and the actual links?  like http://pki.treas.gov/crl_certs.htm

**Comment by dasgituser** [comment]
Jordan,

Hi. I think it is looking good.  I know you are not done tweaking the
playbook, but here are some initial comments:
1. suggest adding physical access to the list of uses
2. suggest making it clear that there is more than PIV.  In FPKI, there is
   also PIV-I, other non-fed certificates, etc.  Pointer to PIV page makes it
   feel like just PIV.
3. suggest not putting dates in document table --- every time a doc is
   updated, we will need to remember to fix it in playbooks.  I think
   playbooks should point to doc landing pages so as to guarantee getting
   latest version;  Pointing to a specific pdf (citing specific date) will
   likely be an ongoing  playbook maintenance hassle.
4. Certificate Profile suddenly appears (all the discussion was about
   certificate policies) without definition/explanation or its relationship to
   certificate policy. Maybe create a new sub-section after Certificate Policy
   that is specifically for Certificate Profile?  Also, regardless of format,
   Certificate Profile references should go with all the other references
   (currently at the end of the playbook) - otherwise just disperse the
   references to appropriate places throughout the playbook -- I like that
   approach better, but is not consistent with Treasury approach.
5. Playbook makes it sound like certificate policy is only about use of a
   cert.  IMHO, certificate policy is more than that (e.g., security around
   issuance, maintenance of certificates, posting information, subscriber
   obligations, etc).  So I think we may want to expand the definition a bit.
6.  I do like the table approach to listing downloadable items such as
   documents.  However, I believe folks are trying to follow the Treasury
   model, which is the list-based approach.  But again, I do like your table
   approach better sans the date column.
7. Real nit:  for the sample certificate content diagram you added
   (different from my sample later in the playbook) -- suggest not using a
   sample that includes an actual FPKI Affiliate Name (Entrust).  We may need
   their permission or other Affiliates may feel we are giving them some
   advantage/endorsement.

**Comment by djpackham** [comment]
@dasgituser 

Thanks again for working on the intro page. I made some edits to your fpki_intro.md pull request. Please let me know what you think. My edits were made on my local repo.
- https://djpackham.github.io/fpki-guides/

Main changes include:
1. Rewording, rearranging, or removing of content
- IMHO some of the content removed can be added to the FPKI Overview page, such as the info about the FPKIPA and FPKIMA Programs
  1. Modified/Added graphics (resized, added captions, titles for 508 compliance, hyperlink to a larger image)

Let me know what you think and we can keep iterating if needed. 

Next, I'll finish my edits for the CRLs and Certificates page.

**Comment by dasgituser** [comment]
Jordan,

Hi.  I think the intro playbook looks great -- thanks for refining.  I
agree that some of the removed content might be good for the overview
playbook.  Let me know if you want to brainstorm that a bit.  I'd be glad
to do another turn on the overview playbook if you want me to.

Thanks
Dave

**Comment by djpackham** [comment]
@dasgituser 

Cool. I can actually submit the changes as a pull request to your original fpki_intro.md file so you don't have to copy and paste from my repo. Then, if you merge my pull request, add any other edits (if needed) then send another pull request to the GSA/fpki-guides, we should be good.

**Pull request merged**
