### PR TITLE
Merge to Production

### PR DESCRIPTION
**Pull request by idmken**

### CODE REVIEW

**Review by ryancdickson — CHANGES_REQUESTED** [review]
@idmken - noticed one typo on the Activity Report page - submitted a PR to address.

Other than that, looks good!

**Review by christyberghoff — APPROVED** [review]

**Review by christyberghoff — APPROVED** [review]

**Review by idmken — COMMENTED** [review]
Looks good.

**Comment by idmken** [comment]
@christyberghoff if you can review the changes, I'll approve it.

**Comment by christyberghoff** [comment]
@idmken Looks good

**Review by christyberghoff — APPROVED** [review]

**Review by ryancdickson — APPROVED** [review]
Looks good to me!

**Pull request merged**
