### PR TITLE
Add testing procedure outline for MS Annoucement

### PR DESCRIPTION
**Pull request by weirdscience**
Quick thoughts on testing procedure outline. Not sure if we want to do a 2nd announcement on testing procedures.

### CODE REVIEW

**Comment by lachellel** [comment]
@weirdscience 

I think we want more detailed test procedures?  This is more of a summary of emails :+1:

**Comment by weirdscience** [comment]
Yep, I put it in as a placeholder to add detail around it.

**Comment by weirdscience** [comment]
@clstmbrly can you QA my additions?

**Comment by weirdscience** [comment]
Maybe better to have a high-level announcement and then a 2nd detailed announcement for admins and engineers. Feedback?

**Comment by clstmbrly** [comment]
@weirdscience I'll review.  Thanks.

**Comment by clstmbrly** [comment]
@weirdscience I've completed QA/edits for this pass.  Please take a look at the coder comments (questions)  in the file.  I know you had some additional changes you wanted to make. After you do that, let me know and I'll re-review.  Thanks!

**Comment by weirdscience** [comment]
@clstmbrly, I did a complete review of the announcement and addressed your comments. Please review when you get a chance.

**Comment by weirdscience** [comment]
I made another commit with new direction to remove COMMON and testing results.

**Comment by clstmbrly** [comment]
@weirdscience  Ready for your review.  Created a new file for the test procedures and added link to MS Hot Topic file.  Sent you an email with some things to note.  Have a great weekend.

**Comment by lachellel** [comment]
i'm closing the pull request - we can open a new clean PR.

**Pull request closed without merging**
