### PR TITLE
UpdateCertificateActivitiesTables

### PR DESCRIPTION
**Pull request by christyberghoff**

### CODE REVIEW

**Comment by idmken** [comment]
@christyberghoff are there more updates or is this all for the month?

**Comment by idmken** [comment]
The repo availability table looks like it was last updated in january 2021. Do you need to update it for March?

**Comment by christyberghoff** [comment]
I've shifted to updating this page as necessary vs. waiting for month's end. These are the current changes and they will changed as we start completing the revocations from FCPCA.

**Comment by christyberghoff** [comment]
The repo availability report has not been updated as some are missing from the listing and others need to be removed from Nagios. I'm working with the ops team to get Nagios updated so that this report will match the report.

**Pull request merged**
