### PR TITLE
20180709 - FPKI Activity Report Update

### PR DESCRIPTION
**Pull request by weirdscience**
- Missed SAFE BioPharma issuances in June update
- Updated Symantec CA to list under DigiCert
- Updated repo availability for June 2018

### CODE REVIEW

**Comment by weirdscience** [comment]
Fixes #270

**Comment by lachellel** [comment]
@weirdscience 

The issued date on the SAFE Biopharma cert is listed as "06/07/2021" (in the future).  I believe this is incorrect?

**Comment by weirdscience** [comment]
Sorry @lachellel the column header should be expiration date not issued date. I fixed it.

**Comment by lachellel** [comment]
no sorry needed!  I simply saw the discrepancy and wasn't sure which was correct!
Merging.

**Pull request merged**
